/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WorkshopsRouteImport } from './routes/workshops'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as BookCallRouteImport } from './routes/book-call'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EnIndexRouteImport } from './routes/en/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as EnWorkshopsRouteImport } from './routes/en/workshops'
import { Route as EnBookCallRouteImport } from './routes/en/book-call'
import { Route as DashboardWorkshopBookingsRouteImport } from './routes/dashboard/workshop-bookings'
import { Route as DashboardBookingsRouteImport } from './routes/dashboard/bookings'
import { Route as DashboardAvailabilityRouteImport } from './routes/dashboard/availability'
import { Route as DashboardCustomersIndexRouteImport } from './routes/dashboard/customers/index'
import { Route as DashboardCustomersIdRouteImport } from './routes/dashboard/customers/$id'

const WorkshopsRoute = WorkshopsRouteImport.update({
  id: '/workshops',
  path: '/workshops',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const BookCallRoute = BookCallRouteImport.update({
  id: '/book-call',
  path: '/book-call',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EnIndexRoute = EnIndexRouteImport.update({
  id: '/en/',
  path: '/en/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const EnWorkshopsRoute = EnWorkshopsRouteImport.update({
  id: '/en/workshops',
  path: '/en/workshops',
  getParentRoute: () => rootRouteImport,
} as any)
const EnBookCallRoute = EnBookCallRouteImport.update({
  id: '/en/book-call',
  path: '/en/book-call',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardWorkshopBookingsRoute =
  DashboardWorkshopBookingsRouteImport.update({
    id: '/workshop-bookings',
    path: '/workshop-bookings',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardBookingsRoute = DashboardBookingsRouteImport.update({
  id: '/bookings',
  path: '/bookings',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAvailabilityRoute = DashboardAvailabilityRouteImport.update({
  id: '/availability',
  path: '/availability',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardCustomersIndexRoute = DashboardCustomersIndexRouteImport.update({
  id: '/customers/',
  path: '/customers/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardCustomersIdRoute = DashboardCustomersIdRouteImport.update({
  id: '/customers/$id',
  path: '/customers/$id',
  getParentRoute: () => DashboardRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/book-call': typeof BookCallRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/workshops': typeof WorkshopsRoute
  '/dashboard/availability': typeof DashboardAvailabilityRoute
  '/dashboard/bookings': typeof DashboardBookingsRoute
  '/dashboard/workshop-bookings': typeof DashboardWorkshopBookingsRoute
  '/en/book-call': typeof EnBookCallRoute
  '/en/workshops': typeof EnWorkshopsRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/en/': typeof EnIndexRoute
  '/dashboard/customers/$id': typeof DashboardCustomersIdRoute
  '/dashboard/customers/': typeof DashboardCustomersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/book-call': typeof BookCallRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/workshops': typeof WorkshopsRoute
  '/dashboard/availability': typeof DashboardAvailabilityRoute
  '/dashboard/bookings': typeof DashboardBookingsRoute
  '/dashboard/workshop-bookings': typeof DashboardWorkshopBookingsRoute
  '/en/book-call': typeof EnBookCallRoute
  '/en/workshops': typeof EnWorkshopsRoute
  '/dashboard': typeof DashboardIndexRoute
  '/en': typeof EnIndexRoute
  '/dashboard/customers/$id': typeof DashboardCustomersIdRoute
  '/dashboard/customers': typeof DashboardCustomersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/book-call': typeof BookCallRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/workshops': typeof WorkshopsRoute
  '/dashboard/availability': typeof DashboardAvailabilityRoute
  '/dashboard/bookings': typeof DashboardBookingsRoute
  '/dashboard/workshop-bookings': typeof DashboardWorkshopBookingsRoute
  '/en/book-call': typeof EnBookCallRoute
  '/en/workshops': typeof EnWorkshopsRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/en/': typeof EnIndexRoute
  '/dashboard/customers/$id': typeof DashboardCustomersIdRoute
  '/dashboard/customers/': typeof DashboardCustomersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/book-call'
    | '/dashboard'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/workshops'
    | '/dashboard/availability'
    | '/dashboard/bookings'
    | '/dashboard/workshop-bookings'
    | '/en/book-call'
    | '/en/workshops'
    | '/dashboard/'
    | '/en/'
    | '/dashboard/customers/$id'
    | '/dashboard/customers/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/book-call'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/workshops'
    | '/dashboard/availability'
    | '/dashboard/bookings'
    | '/dashboard/workshop-bookings'
    | '/en/book-call'
    | '/en/workshops'
    | '/dashboard'
    | '/en'
    | '/dashboard/customers/$id'
    | '/dashboard/customers'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/book-call'
    | '/dashboard'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/workshops'
    | '/dashboard/availability'
    | '/dashboard/bookings'
    | '/dashboard/workshop-bookings'
    | '/en/book-call'
    | '/en/workshops'
    | '/dashboard/'
    | '/en/'
    | '/dashboard/customers/$id'
    | '/dashboard/customers/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  BookCallRoute: typeof BookCallRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  WorkshopsRoute: typeof WorkshopsRoute
  EnBookCallRoute: typeof EnBookCallRoute
  EnWorkshopsRoute: typeof EnWorkshopsRoute
  EnIndexRoute: typeof EnIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/workshops': {
      id: '/workshops'
      path: '/workshops'
      fullPath: '/workshops'
      preLoaderRoute: typeof WorkshopsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book-call': {
      id: '/book-call'
      path: '/book-call'
      fullPath: '/book-call'
      preLoaderRoute: typeof BookCallRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en/': {
      id: '/en/'
      path: '/en'
      fullPath: '/en/'
      preLoaderRoute: typeof EnIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/en/workshops': {
      id: '/en/workshops'
      path: '/en/workshops'
      fullPath: '/en/workshops'
      preLoaderRoute: typeof EnWorkshopsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en/book-call': {
      id: '/en/book-call'
      path: '/en/book-call'
      fullPath: '/en/book-call'
      preLoaderRoute: typeof EnBookCallRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/workshop-bookings': {
      id: '/dashboard/workshop-bookings'
      path: '/workshop-bookings'
      fullPath: '/dashboard/workshop-bookings'
      preLoaderRoute: typeof DashboardWorkshopBookingsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/bookings': {
      id: '/dashboard/bookings'
      path: '/bookings'
      fullPath: '/dashboard/bookings'
      preLoaderRoute: typeof DashboardBookingsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/availability': {
      id: '/dashboard/availability'
      path: '/availability'
      fullPath: '/dashboard/availability'
      preLoaderRoute: typeof DashboardAvailabilityRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/customers/': {
      id: '/dashboard/customers/'
      path: '/customers'
      fullPath: '/dashboard/customers/'
      preLoaderRoute: typeof DashboardCustomersIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/customers/$id': {
      id: '/dashboard/customers/$id'
      path: '/customers/$id'
      fullPath: '/dashboard/customers/$id'
      preLoaderRoute: typeof DashboardCustomersIdRouteImport
      parentRoute: typeof DashboardRoute
    }
  }
}

interface DashboardRouteChildren {
  DashboardAvailabilityRoute: typeof DashboardAvailabilityRoute
  DashboardBookingsRoute: typeof DashboardBookingsRoute
  DashboardWorkshopBookingsRoute: typeof DashboardWorkshopBookingsRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardCustomersIdRoute: typeof DashboardCustomersIdRoute
  DashboardCustomersIndexRoute: typeof DashboardCustomersIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardAvailabilityRoute: DashboardAvailabilityRoute,
  DashboardBookingsRoute: DashboardBookingsRoute,
  DashboardWorkshopBookingsRoute: DashboardWorkshopBookingsRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardCustomersIdRoute: DashboardCustomersIdRoute,
  DashboardCustomersIndexRoute: DashboardCustomersIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  BookCallRoute: BookCallRoute,
  DashboardRoute: DashboardRouteWithChildren,
  RobotsDottxtRoute: RobotsDottxtRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  WorkshopsRoute: WorkshopsRoute,
  EnBookCallRoute: EnBookCallRoute,
  EnWorkshopsRoute: EnWorkshopsRoute,
  EnIndexRoute: EnIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
